"""nginx front-end for a multi-instance deployment.

Runs unprivileged: every path nginx wants to write (pid file, temp dirs, logs) is redirected
under the run's output directory, and it listens on a high port, so no root and no system
nginx config are involved.

Streaming-related settings, and what is actually known about them:

  `proxy_buffering off` / `postpone_output 0` are the standard, documented settings for
  proxying Server-Sent Events, and are kept as insurance. They are NOT, however, load-bearing
  on the nginx build tested here: measured against a fake SSE upstream on nginx 1.18 at
  inter-token intervals from 40ms down to 0.2ms, buffering on and off produced identical
  median ITL to two decimal places. nginx forwards a `text/event-stream` response as data
  arrives rather than withholding it to fill a buffer, as long as the client keeps up. Keep
  them anyway -- they cost nothing and other versions, or a gzip/`sub_filter` in the chain,
  do behave differently -- but do not attribute a latency result to them without measuring.

  `proxy_read_timeout` -- a CPU-backend prefill of a long prompt can exceed nginx's 60s
  default, which would surface as a 504 mid-benchmark and be recorded as a backend failure
  when it was really the proxy giving up. Tied to the spec's request timeout. This one does
  matter in practice on this hardware.

nginx is inside the measured window when it is used. That is the point of the option -- it is
the production topology -- but the report labels those rows so they are never silently
compared against direct-to-instance numbers.
"""
from __future__ import annotations

import shutil
from pathlib import Path

from ..plan import DeploymentPlan
from ..spec import SuiteSpec

NGINX_CONF_TEMPLATE = """# Generated by llmbench -- do not edit; regenerated on every deployment.
# deployment: {dep_id}  backend: {backend}  instances: {n_instances}
daemon off;
master_process on;
worker_processes {worker_processes};
pid {pid_path};
error_log {error_log} {error_level};
worker_rlimit_nofile 65536;

events {{
    worker_connections 8192;
    multi_accept on;
}}

http {{
    access_log {access_log};
    default_type application/octet-stream;

    client_body_temp_path {tmp}/client_body;
    proxy_temp_path       {tmp}/proxy;
    fastcgi_temp_path     {tmp}/fastcgi;
    uwsgi_temp_path       {tmp}/uwsgi;
    scgi_temp_path        {tmp}/scgi;

    tcp_nodelay on;
    sendfile off;
    keepalive_timeout 300s;

    # Disables nginx withholding output until it has `postpone_output` bytes (default 1460).
    # Documented correct setting for a streaming proxy; measured no effect here (see docstring).
    postpone_output 0;

    upstream llmbench_upstream {{
        {balancing}
{servers}
        keepalive {keepalive};
        keepalive_requests 100000;
    }}

    server {{
        listen {listen_port} backlog=8192;
        server_name _;

        location / {{
            proxy_pass http://llmbench_upstream;

            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;

            # Standard SSE pass-through settings, kept as insurance. Measured no effect on
            # ITL on nginx 1.18 here (see module docstring) -- do not credit them for a
            # latency result without measuring on your build.
            proxy_buffering off;
            proxy_request_buffering off;
            gzip off;
            chunked_transfer_encoding on;

            proxy_connect_timeout {connect_timeout}s;
            proxy_send_timeout {read_timeout}s;
            proxy_read_timeout {read_timeout}s;

            # Do not silently retry onto another instance: a retried request would be timed
            # as one slow request and would quietly hide a failing backend.
            proxy_next_upstream off;
        }}
    }}
}}
"""


class NginxUnavailable(RuntimeError):
    pass


# nginx is normally installed into sbin, which is frequently absent from a non-root PATH
# (and always absent under cron/systemd). Look there before giving up.
_FALLBACK_DIRS = ("/usr/sbin", "/usr/local/sbin", "/sbin", "/usr/local/nginx/sbin")

# `-e <file>` (set the error log from the command line) only exists from nginx 1.19.5. On
# older builds passing it is a hard "invalid option" failure.
_MIN_DASH_E = (1, 19, 5)


def resolve_nginx(bin_name: str = "nginx") -> str:
    exe = shutil.which(bin_name) or (bin_name if Path(bin_name).is_file() else None)
    if not exe:
        for d in _FALLBACK_DIRS:
            candidate = Path(d) / bin_name
            if candidate.is_file():
                exe = str(candidate)
                break
    if not exe:
        raise NginxUnavailable(
            f"lb.kind=nginx was requested but {bin_name!r} was not found on PATH "
            f"(also looked in {', '.join(_FALLBACK_DIRS)}).\n"
            f"  install it:  sudo apt-get install -y nginx-light\n"
            f"  or set an explicit path:  lb: {{ nginx_bin: /usr/sbin/nginx }}\n"
            f"  or switch to the no-proxy path, which needs nothing installed and keeps the\n"
            f"  proxy hop out of the measured window:  lb: {{ kind: client }}"
        )
    return exe


def nginx_version(exe: str) -> tuple[int, ...]:
    """Parse `nginx -v` (which writes to stderr). Returns () if it cannot be determined."""
    import re
    import subprocess

    try:
        out = subprocess.run([exe, "-v"], capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return ()
    m = re.search(r"nginx/(\d+)\.(\d+)\.(\d+)", (out.stderr or "") + (out.stdout or ""))
    return tuple(int(g) for g in m.groups()) if m else ()


def render_conf(dep: DeploymentPlan, spec: SuiteSpec, *, conf_dir: Path, log_dir: Path) -> str:
    tmp = conf_dir / "tmp"
    servers = "\n".join(
        f"        server 127.0.0.1:{i.port} max_fails=0;" for i in dep.instances
    )
    # least_conn matches the client-side default (least-outstanding) so the two LB modes are
    # comparing the same policy; round-robin is nginx's implicit default and needs no directive.
    balancing = "least_conn;" if spec.lb.strategy == "least-outstanding" else "# round-robin (nginx default)"
    workers = spec.lb.worker_processes or (
        len(dep.lb_placement.cpus) if dep.lb_placement else 4
    )
    return NGINX_CONF_TEMPLATE.format(
        dep_id=dep.id, backend=dep.backend, n_instances=dep.n_instances,
        worker_processes=max(1, workers),
        pid_path=conf_dir / "nginx.pid",
        error_log=log_dir / "nginx-error.log",
        error_level="warn",
        access_log="off",
        tmp=tmp,
        balancing=balancing,
        servers=servers,
        keepalive=max(32, dep.n_instances * 64),
        listen_port=dep.lb_port,
        connect_timeout=10,
        read_timeout=int(spec.request_timeout_s),
    )


def prepare(dep: DeploymentPlan, spec: SuiteSpec, *, out_dir: Path) -> tuple[str, Path, Path]:
    """Write the config and create every directory nginx needs to write into.

    Returns (nginx_exe, conf_path, prefix_dir).
    """
    exe = resolve_nginx(spec.lb.nginx_bin)
    conf_dir = out_dir / "nginx" / dep.id
    log_dir = out_dir / "logs" / dep.id
    for d in (conf_dir, conf_dir / "tmp", log_dir):
        d.mkdir(parents=True, exist_ok=True)

    conf_path = conf_dir / "nginx.conf"
    conf_path.write_text(render_conf(dep, spec, conf_dir=conf_dir, log_dir=log_dir))
    return exe, conf_path, conf_dir


def build_argv(exe: str, conf_path: Path, prefix: Path, dep: DeploymentPlan, spec) -> list[str]:
    """nginx pinned to the auxiliary cpus, so it cannot steal cores from the instances."""
    from ..deploy import numactl_prefix

    argv: list[str] = []
    if dep.lb_placement and dep.lb_placement.cpus:
        from ..topology import CoreSet

        aux = CoreSet(
            index=-1, cpus=list(dep.lb_placement.cpus),
            physical_cpus=list(dep.lb_placement.cpus),
            nodes=list(dep.lb_placement.membind), sockets=[], ccds=[],
            membind=list(dep.lb_placement.membind),
        )
        argv += numactl_prefix(aux, spec.cpu) + ["--"]
    argv += [exe, "-c", str(conf_path), "-p", str(prefix)]
    # Redirect the *early* error log -- the one nginx opens before it has parsed our config,
    # which otherwise points at the compiled-in /var/log/nginx/error.log and is unwritable
    # when running unprivileged. Only from 1.19.5; older nginx rejects `-e` outright, and the
    # resulting alert about the default log is noisy but harmless (it still starts and binds).
    if nginx_version(exe) >= _MIN_DASH_E:
        argv += ["-e", str(prefix / "nginx-early.log")]
    return argv


__all__ = ["prepare", "build_argv", "render_conf", "resolve_nginx", "NginxUnavailable"]
